# Generated by Django 3.2.7 on 2021-09-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('rollNa', models.CharField(max_length=15)),
                ('dept', models.CharField(max_length=30)),
                ('addmission', models.DateField()),
                ('iamge', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
